[workspace]
resolver = "2"
members = [
    "arkworks",
    "arkworks3",
    "arkworks3-sppark",
    "arkworks3-sppark-wlc",
    "blst",
    "blst-sppark",
    "kzg",
    "kzg-bench",
    "mcl/kzg",
    "mcl/kzg-bench",
    "zkcrypto",
    "constantine"
]


[profile.bench]
lto = "thin"
