name: blst tests

on: [push, pull_request, workflow_dispatch]

env:
  C_KZG_4844_GIT_HASH: 'a1d03803059471948e518820afa8518643e1b638'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-11]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py_ecc
          pip install PyYAML

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.19

      - name: "[blst][wasm32] Clippy"
        # Apple's Clang doesn't support WASM, and we are lazy to install it
        if: runner.os != 'macOS'
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path blst/Cargo.toml --target wasm32-unknown-unknown --no-default-features

      - name: "[blst][wasm32] Build"
        # Apple's Clang doesn't support WASM, and we are lazy to install it
        if: runner.os != 'macOS'
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path blst/Cargo.toml --target wasm32-unknown-unknown --no-default-features

      - name: "[blst] Tests (minimal preset)"
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path blst/Cargo.toml --no-fail-fast --test eip_4844 tests --features minimal-spec

      - name: "[blst] Tests (mainnet preset)"
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path blst/Cargo.toml --no-fail-fast

      - name: "[blst] Tests (mainnet preset, parallel)"
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path blst/Cargo.toml --no-fail-fast --features parallel

      - name: "[blst] Tests (c-kzg-4844)"
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd blst && bash run-c-kzg-4844-tests.sh

      - name: "[blst] Tests (c-kzg-4844 parallel)"
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd blst && bash run-c-kzg-4844-tests.sh --parallel

      - name: "[blst] Clippy"
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path blst/Cargo.toml --all-targets --features=default,std,rand,parallel,minimal-spec -- -D warnings

      - name: "[blst] Formatting"
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path blst/Cargo.toml -- --check

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path kzg-bench/Cargo.toml -- --check
