name: blst benchmarks

on: [push, pull_request, workflow_dispatch]

env:
  C_KZG_4844_GIT_HASH: 'a1d03803059471948e518820afa8518643e1b638'

jobs:
  benchmarks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-11]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.19

      - name: "[blst] Benchmark"
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --manifest-path blst/Cargo.toml

      - name: "[blst] Benchmark (parallel)"
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --manifest-path blst/Cargo.toml --features parallel

      - name: "[blst] Benchmark (c-kzg-4844)"
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd blst && bash run-c-kzg-4844-benches.sh

      - name: "[blst] Benchmark (c-kzg-4844 parallel)"
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd blst && bash run-c-kzg-4844-benches.sh --parallel
