name: zkcrypto benchmarks

on: [push, pull_request, workflow_dispatch]

env:
  C_KZG_4844_GIT_HASH: '624aa60d01da524827123506975431aa5454c80d'

jobs:
  benchmarks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-11]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.19

      - name: "[zkcrypto] Benchmark"
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --manifest-path zkcrypto/Cargo.toml

      - name: "[zkcrypto] Benchmark (parallel)"
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --manifest-path zkcrypto/Cargo.toml --features parallel

      - name: "[zkcrypto] Benchmark (c-kzg-4844)"
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd zkcrypto && bash run-c-kzg-4844-benches.sh

      - name: "[zkcrypto] Benchmark (c-kzg-4844 parallel)"
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd zkcrypto && bash run-c-kzg-4844-benches.sh --parallel
